### ISSUE TITLE
Error sending timezone-aware timestamps

### ISSUE THREAD

**Issue by adamroth** [customerio/customerio-python#17]
In my Django 1.8 project configured to be timezone aware (`USE_TZ=True` in Django settings), I have a `created_at` timestamp field on my user model which is a standard Django `DateTimeField`. I get the following error when attempting to send this field over to CustomerIO via the python client:

```
  File ".../customerio/__init__.py", line 71, in identify
    self.send_request('PUT', url, kwargs)
  File ".../customerio/__init__.py", line 50, in send_request
    data = json.dumps(self._sanitize(data), cls=self.json_encoder)
  File ".../customerio/__init__.py", line 121, in _sanitize
    data[k] = self._timedelta_to_timestamp(v - datetime(1970, 1, 1))
TypeError: can't subtract offset-naive and offset-aware datetimes
```

Should the python client support this?

**Comment by hownowstephen** [comment]
This should be fixed in the [latest version](https://github.com/customerio/customerio-python/tree/v0.1.9) - v0.1.9 now available on PyPI. Thanks for letting me know!

**Comment by adamroth** [comment]
Thanks @hownowstephen, looks good I'll give it a shot!
