### ISSUE TITLE
Calls with NaN values are processed by customerio-python, but are not reflected in the interface

### ISSUE THREAD

**Issue by niparis** [customerio/customerio-python#35]
if one of the arguments of the identify method has value math.nan, no exception is given by the API (ie: returns 200), however, the customer is not saved/updated.

Example:

```
import math
from customerio import CustomerIO

cio = CustomerIO(site_id, api_key)
data = {'id': 1, 'email': 'test@test.test', 'value': math.nan}
cio.identify(**data}
```

Expected: a user with email test@test.test should appear in the interface.
Actual: code runs fine, nothing happens in interface

**Comment by hownowstephen** [comment]
closing as the associated PR has been merged
