### ISSUE TITLE
Trigger Broadcast API

### ISSUE THREAD

**Issue by scottgeye** [customerio/customerio-python#40]
Are there any plans to support the latest API features in python?  Thanks!

**Comment by hownowstephen** [comment]
As the use case / information required to be successful with API triggered broadcasts is quite different from our standard streaming API, we've opted to leave it off our integration libraries for the time being.

The endpoint is RESTful, so your best option for setting it up is to call out to our API directly using a raw `requests.post` with your API credentials [as described in our API docs](https://learn.customer.io/api/#apibroadcast_trigger) to the endpoint at

```
https://api.customer.io/v1/api/campaigns/:id/triggers
```

thanks for the interest, and as always, feel free to contact us at win@customer.io if you need any further help getting set up to send out broadcasts!
